import React, { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams, useNavigation } from 'expo-router';
import { REPORT_DEFINITIONS } from '../../data/mockData';
import { useApp } from '../../context/AppContext';
import { ROLE_ACTOR, type HospitalProfile } from '../../logic/hospital';
import { buildReport, type ReportData } from '../../logic/reports';
import { colors, radius, shadows, spacing, typography } from '../../constants/theme';
import { Header } from '../../components/common/Header';
import { EmptyState } from '../../components/common/EmptyState';
import { FadeInView, PulseDot, Skeleton, stagger } from '../../components/common/Motion';
import { BottomActionBar, useBottomBarSpace } from '../../components/common/BottomActionBar';
import { BarChart } from '../../components/finance/BarChart';
import { ExportActions } from '../../components/finance/ExportActions';
import { KpiTile } from '../../components/finance/KpiTile';
import { ReportTable } from '../../components/finance/ReportTable';
import { openBillingTab, pushOrPopTo } from '../../components/finance/financeNavigation';
import { hospitalHeader, type IconName } from '../../components/finance/invoiceUtils';
import { exportDocument, type DocumentSpec, type ExportAction } from '../../utils/pdfGenerator';
import { formatCompactCurrency } from '../../utils/formatters';
import { todayISO } from '../../utils/dates';

const KPI_COLORS = ['#1E6BFF', '#10B981', '#F59E0B', '#8B5CF6'];

const chartValue = (n: number, unit: ReportData['chartUnit']) =>
  unit === 'currency' ? formatCompactCurrency(n) : unit === 'percent' ? `${Math.round(n)}%` : String(Math.round(n));

const chartColumnLabel: Record<NonNullable<ReportData['chartUnit']>, string> = {
  currency: 'Amount',
  count: 'Count',
  percent: 'Percent',
};

/** ReportData → printable document (same content as the screen). */
const toDocumentSpec = (r: ReportData, hospital: HospitalProfile, preparedBy: string): DocumentSpec => ({
  title: r.title,
  subtitle: r.subtitle,
  meta: [
    ['Category', `${r.category} report`],
    ['Generated', r.generatedAt],
    ['Prepared by', preparedBy],
  ],
  sections: [
    { heading: 'Summary', rows: r.kpis.map((k) => [k.label, k.value] as [string, string]) },
    ...(r.chart?.length
      ? [
          {
            heading: r.chartTitle ?? 'Breakdown',
            table: {
              columns: ['Segment', chartColumnLabel[r.chartUnit ?? 'count']],
              rows: r.chart.map((c) => [c.label, chartValue(c.value, r.chartUnit)]),
              alignRight: [1],
            },
          },
        ]
      : []),
    r.rows.length
      ? { heading: 'Details', table: { columns: r.columns, rows: r.rows, alignRight: r.alignRight } }
      : { heading: 'Details', paragraphs: ['No records for this report yet.'] },
    ...(r.notes?.length ? [{ heading: 'Notes', bullets: r.notes }] : []),
  ],
  signatory: preparedBy,
  signatoryRole: 'Prepared by',
  footer: `Generated by CareSync on ${r.generatedAt} • computer-generated report`,
  hospital: hospitalHeader(hospital),
});

type Related = { label: string; icon: IconName; onPress: () => void };

export default function ReportDetailRoute() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const app = useApp();
  const navigation = useNavigation();
  const bottomSpace = useBottomBarSpace(84);
  const [ready, setReady] = useState(false);
  const [nonce, setNonce] = useState(0);

  const reportId = String(id ?? '');
  const def = REPORT_DEFINITIONS.find((d) => d.id === reportId);

  // Short "compiling" beat on open / refresh so regenerated figures read as fresh.
  useEffect(() => {
    setReady(false);
    const t = setTimeout(() => setReady(true), 450);
    return () => clearTimeout(t);
  }, [reportId, nonce]);

  const report = useMemo(() => buildReport(reportId, app), [reportId, app, nonce]);

  if (!report || !def) {
    return (
      <SafeAreaView edges={['top', 'left', 'right']} style={styles.safeArea}>
        <Header title="Report" showBack />
        <EmptyState
          icon="bar-chart-outline"
          title="Report not found"
          description="This report doesn't exist or the link is out of date."
          actionTitle="All Reports"
          onActionPress={() => pushOrPopTo(navigation.getState(), 'reports', '/reports')}
          style={styles.empty}
        />
      </SafeAreaView>
    );
  }

  const preparedBy = ROLE_ACTOR[app.activeRole] ?? 'CareSync';
  const exportReport = (action: ExportAction) =>
    exportDocument(toDocumentSpec(report, app.hospitalProfile, preparedBy), `${report.title.replace(/[^\w]+/g, '-')}-${todayISO()}.pdf`, action);

  const related: Related[] = [];
  if (report.category === 'Financial') {
    related.push({
      label: 'Financial Management',
      icon: 'stats-chart-outline',
      onPress: () => pushOrPopTo(navigation.getState(), 'financial-management', '/financial-management'),
    });
  }
  const push = (label: string, icon: IconName, path: string) => related.push({ label, icon, onPress: () => router.push(path as never) });
  switch (report.id) {
    case 'daily-collection':
    case 'opd-collection':
      related.push({ label: 'Billing & Invoices', icon: 'receipt-outline', onPress: () => openBillingTab() });
      break;
    case 'ipd-admission':
    case 'admissions-discharges':
    case 'bed-occupancy':
      push('Bed Management', 'bed-outline', '/bed-management');
      break;
    case 'pharmacy-sales':
      push('Pharmacy', 'bandage-outline', '/pharmacy');
      break;
    case 'lab-radiology':
    case 'lab-tat':
      push('Lab Portal', 'flask-outline', '/lab-portal');
      break;
    case 'doctor-wise':
    case 'follow-ups':
      push('Appointments', 'calendar-outline', '/appointments');
      break;
    case 'inventory-status':
      push('Inventory', 'cube-outline', '/inventory');
      break;
    case 'patient-register':
      related.push({ label: 'Patients', icon: 'people-outline', onPress: () => router.dismissTo('/(tabs)/patients') });
      break;
  }

  const hasChart = !!report.chart?.length && report.chart.some((c) => c.value > 0);

  return (
    <SafeAreaView edges={['top', 'left', 'right']} style={styles.safeArea}>
      <Header
        title={report.title}
        subtitle={`Generated ${report.generatedAt}`}
        showBack
        rightAction={
          <TouchableOpacity
            style={styles.headerBtn}
            onPress={() => setNonce((n) => n + 1)}
            accessibilityRole="button"
            accessibilityLabel="Regenerate report"
            hitSlop={6}
          >
            <Ionicons name="refresh-outline" size={20} color={colors.primary} />
          </TouchableOpacity>
        }
      />

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={[styles.content, { paddingBottom: bottomSpace + spacing.base }]}
      >
        <FadeInView>
          <View style={styles.intro}>
            <View style={[styles.introIcon, { backgroundColor: def.color + '18' }]}>
              <Ionicons name={def.icon as IconName} size={20} color={def.color} />
            </View>
            <View style={{ flex: 1 }}>
              <View style={styles.chipRow}>
                <View style={[styles.chip, { backgroundColor: def.color + '18' }]}>
                  <Text style={[styles.chipText, { color: def.color }]}>{report.category}</Text>
                </View>
                <View style={styles.liveChip}>
                  <PulseDot size={6} />
                  <Text style={styles.liveText}>Live data</Text>
                </View>
              </View>
              <Text style={styles.introText}>{report.subtitle}</Text>
            </View>
          </View>
        </FadeInView>

        {!ready ? (
          <View accessibilityLabel="Compiling report">
            <View style={styles.kpiGrid}>
              {[0, 1, 2, 3].map((i) => (
                <View key={i} style={[styles.kpiCell, styles.skeletonTile]}>
                  <Skeleton width="60%" height={10} />
                  <Skeleton width="80%" height={20} style={{ marginTop: 10 }} />
                </View>
              ))}
            </View>
            <View style={styles.card}>
              <Skeleton width="40%" height={12} />
              <Skeleton height={110} radius={10} style={{ marginTop: spacing.md }} />
            </View>
            <View style={styles.card}>
              {[0, 1, 2, 3, 4].map((i) => (
                <Skeleton key={i} height={12} style={{ marginBottom: 12 }} />
              ))}
            </View>
          </View>
        ) : (
          <>
            <View style={styles.kpiGrid}>
              {report.kpis.map((k, i) => (
                <FadeInView key={`${nonce}-${k.label}`} delay={stagger(i, 60)} style={styles.kpiCell}>
                  <KpiTile label={k.label} value={k.value} color={i === 0 ? def.color : KPI_COLORS[i % KPI_COLORS.length]} delay={stagger(i, 60)} />
                </FadeInView>
              ))}
            </View>

            {hasChart && (
              <FadeInView delay={220}>
                <View style={styles.card}>
                  <Text style={styles.cardTitle}>{report.chartTitle ?? 'Breakdown'}</Text>
                  <BarChart
                    key={nonce}
                    data={report.chart!}
                    height={120}
                    barMaxWidth={32}
                    color={def.color + '55'}
                    highlightColor={def.color}
                    showValues={report.chart!.length <= 6 ? 'all' : 'max'}
                    formatValue={(n) => chartValue(n, report.chartUnit)}
                    accessibilityTitle={report.chartTitle ?? report.title}
                    style={{ marginTop: spacing.md }}
                  />
                </View>
              </FadeInView>
            )}

            <FadeInView delay={280}>
              <View style={styles.card}>
                <View style={styles.cardHead}>
                  <Text style={styles.cardTitle}>Details</Text>
                  <Text style={styles.cardMeta}>
                    {report.rows.length} row{report.rows.length === 1 ? '' : 's'}
                  </Text>
                </View>
                <ReportTable columns={report.columns} rows={report.rows} alignRight={report.alignRight} />
              </View>
            </FadeInView>

            {!!report.notes?.length && (
              <FadeInView delay={340}>
                <View style={styles.card}>
                  <Text style={styles.cardTitle}>Notes</Text>
                  {report.notes.map((n, i) => (
                    <View key={i} style={styles.noteRow}>
                      <View style={[styles.noteDot, { backgroundColor: def.color }]} />
                      <Text style={styles.noteText}>{n}</Text>
                    </View>
                  ))}
                </View>
              </FadeInView>
            )}

            {related.length > 0 && (
              <FadeInView delay={380}>
                <View style={styles.relatedRow}>
                  {related.map((r) => (
                    <TouchableOpacity key={r.label} style={styles.related} onPress={r.onPress} accessibilityRole="link">
                      <Ionicons name={r.icon} size={16} color={colors.primary} />
                      <Text style={styles.relatedText}>{r.label}</Text>
                      <Ionicons name="chevron-forward" size={14} color={colors.primary} />
                    </TouchableOpacity>
                  ))}
                </View>
              </FadeInView>
            )}
          </>
        )}
      </ScrollView>

      <BottomActionBar>
        <ExportActions layout="row" onExport={exportReport} disabled={!ready} labels={{ download: 'Export PDF' }} />
      </BottomActionBar>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  empty: {
    flex: 1,
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    padding: spacing.base,
  },
  intro: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.base,
  },
  introIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  chip: {
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  chipText: {
    fontSize: 11,
    fontWeight: typography.fontWeights.bold,
  },
  liveChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  liveText: {
    fontSize: 11,
    color: colors.success,
    fontWeight: typography.fontWeights.semiBold,
  },
  introText: {
    fontSize: typography.fontSizes.sm,
    color: colors.textSecondary,
    marginTop: 6,
    lineHeight: 18,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.md,
    marginBottom: spacing.md,
  },
  kpiCell: {
    width: '48.3%',
  },
  skeletonTile: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: spacing.md,
    minHeight: 78,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  cardTitle: {
    fontSize: typography.fontSizes.sm + 1,
    fontWeight: typography.fontWeights.bold,
    color: colors.text,
  },
  cardMeta: {
    fontSize: typography.fontSizes.xs,
    color: colors.textMuted,
    fontWeight: typography.fontWeights.semiBold,
  },
  noteRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  noteDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 6,
  },
  noteText: {
    flex: 1,
    fontSize: typography.fontSizes.sm,
    color: colors.text,
    lineHeight: 19,
  },
  relatedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  related: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
    backgroundColor: colors.primaryLight,
  },
  relatedText: {
    fontSize: typography.fontSizes.sm,
    fontWeight: typography.fontWeights.semiBold,
    color: colors.primary,
  },
});
